"""update member fields and account data

Revision ID: da856d8408a2
Revises: e9c5703e681f
Create Date: 2026-08-21 15:29:39.128041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da856d8408a2'
down_revision: Union[str, Sequence[str], None] = 'e9c5703e681f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('membership_type', sa.String(length=100), nullable=False))
    op.add_column('members', sa.Column('email_address', sa.String(length=255), nullable=True))
    op.add_column('members', sa.Column('church_branch', sa.String(length=150), nullable=True))
    op.add_column('members', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('members', sa.Column('accounts', postgresql.ARRAY(sa.String()), nullable=False))
    op.add_column('members', sa.Column('gps_address', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_members_phone_number'), table_name='members')
    op.drop_constraint(op.f('members_email_key'), 'members', type_='unique')
    op.drop_column('members', 'membership_status')
    op.drop_column('members', 'church')
    op.drop_column('members', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('members', sa.Column('church', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('members', sa.Column('membership_status', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('members_email_key'), 'members', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_members_phone_number'), 'members', ['phone_number'], unique=True)
    op.drop_column('members', 'gps_address')
    op.drop_column('members', 'accounts')
    op.drop_column('members', 'is_active')
    op.drop_column('members', 'church_branch')
    op.drop_column('members', 'email_address')
    op.drop_column('members', 'membership_type')
    # ### end Alembic commands ###
